#+property: header-args :tangle yes
* Header
** configuration
*** custom file
#+begin_src emacs-lisp
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
  (load custom-file))
#+end_src
*** straight.el
    :properties:
    :header-args: :tangle :no
    :end:
    we add this because it allows us to directly
    build from git repos, we need this in particular
    for org-mode
#+BEGIN_SRC emacs-lisp
(let ((bootstrap-file (concat user-emacs-directory "straight/repos/straight.el/bootstrap.el"))
      (bootstrap-version 3))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
#+END_SRC
*** package.el
    :properties:
    :header-args: :tangle yes
    :end:
#+begin_src emacs-lisp
  (require 'package)
  (add-to-list 'package-archives
               '("melpa" . "https://melpa.org/packages/") t)
  (add-to-list 'package-archives
               '("org" . "https://orgmode.org/elpa/") t)
#+end_src

*** use-package
**** package.el mode
     :properties:
     :header-args: :tangle yes
     :end:
#+begin_src emacs-lisp
(unless package-archive-contents
  (package-refresh-contents))

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(setq use-package-always-ensure t)
#+end_src
**** straight.el mode
:properties:
:header-args: :tangle no
:end:
#+BEGIN_SRC emacs-lisp
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
#+END_SRC

*** org-hack
:properties:
:header-args: :tangle :no
:end:
#+begin_src emacs-lisp
(require 'subr-x)
(straight-use-package 'git)
(defun org-git-version ()
  "The Git version of org-mode.
Inserted by installing org-mode or when a release is made."
  (require 'git)
  (let ((git-repo (expand-file-name
                   "straight/repos/org/" user-emacs-directory)))
    (string-trim
     (git-run "describe"
              "--match=release\*"
              "--abbrev=6"
              "HEAD"))))

(defun org-release ()
  "The release version of org-mode.
Inserted by installing org-mode or when a release is made."
  (require 'git)
  (let ((git-repo (expand-file-name
                   "straight/repos/org/" user-emacs-directory)))
    (string-trim
     (string-remove-prefix
      "release_"
      (git-run "describe"
               "--match=release\*"
               "--abbrev=0"
               "HEAD")))))

(provide 'org-version)
#+end_src
* packages
** use-package
#+begin_src emacs-lisp
(use-package use-package)
#+end_src
*** use-package-chords
#+begin_src emacs-lisp
  (use-package use-package-chords
    :config (key-chord-mode 1))
#+end_src
** no littering 
#+begin_src emacs-lisp
(use-package no-littering)
#+end_src
** evil
#+begin_src emacs-lisp
(use-package evil
	     :config (evil-mode 1))
#+end_src
*** evil plugins
**** evil-org
#+begin_src emacs-lisp
  (use-package evil-org
    :after org
    :hook
    (org-mode . evil-org-mode)
    (evil-org-mode . evil-org-set-key-theme)
    :requires evil-org-agenda
    :config (evil-org-agenda-set-keys))
#+end_src
**** evil-magit
#+BEGIN_SRC emacs-lisp
(use-package evil-magit)
#+END_SRC
** emamux
This package lets us send commands to tmux, it's very handy
#+BEGIN_SRC emacs-lisp
  (use-package emamux
    :bind-keymap (("C-`" . emamux:keymap))
    :chords (("``" . emamux:send-region)))
#+END_SRC
** org
   :properties:
   :header-args: :tangle yes
   :end:
#+begin_src emacs-lisp
  (use-package org
    :config
    (require 'org-mouse)
    :custom (org-src-fontify-natively t)
    :ensure org-plus-contrib)
#+end_src
*** ob-async
This allows task execution in parrallel
#+BEGIN_SRC emacs-lisp
(use-package ob-async)
#+END_SRC
** htmlize
#+begin_src emacs-lisp	
  (use-package htmlize)
#+end_src
** ivy
#+begin_src emacs-lisp
  (use-package ivy
    :config (ivy-mode)
    :custom
    (ivy-use-virtual-buffers t)
    (ivy-count-format "(%d/%d) "))
#+end_src
** counsel
#+begin_src emacs-lisp
  (use-package counsel
    :config (counsel-mode))
#+end_src
*** counsel plugins
**** projectile
#+begin_src emacs-lisp
  (use-package counsel-projectile
    :config (counsel-projectile-mode))
#+end_src
** which key
#+begin_src emacs-lisp
  (use-package which-key
    :config (which-key-mode))
#+end_src
** projectile
#+begin_src emacs-lisp
  (use-package projectile
    :config (projectile-mode))
#+end_src
** rainbow delimeters
#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook
    (c-mode . rainbow-delimeters-mode)
    (c++-mode . rainbow-delimeters-mode)
    (python-mode . rainbow-delimeters-mode))
#+end_src
** company
#+begin_src emacs-lisp
  (use-package company
    :config
    (global-company-mode)
    :custom
    (company-idle-delay 0)
    (company-minimum-prefix-length 2))
#+end_src
*** irony
#+BEGIN_SRC emacs-lisp
  (use-package company-irony
    :config
    (add-to-list 'company-backends 'company-irony))
#+END_SRC
*** c-headers
#+begin_src emacs-lisp
  (use-package company-c-headers
    :config
    (add-to-list 'company-backends 'company-c-headers))
#+end_src
*** company-math
    This adds math symbols and unicode things
#+BEGIN_SRC emacs-lisp
  (use-package company-math
    :config (add-to-list 'company-backends 'company-math-symbols-unicode))
#+END_SRC
*** company-box
    This package adds a frontend to company that uses a  real box
    This is nice because it works with variable pitch fonts, and can have
    colors and whatnot. Also it can extend off the side of the emacs window.
    This does require emacs 26 or above however.
    #+BEGIN_SRC emacs-lisp
    (if (version< "26" emacs-version)
      (use-package company-box
	:hook (company-mode . company-box-mode)))
    #+END_SRC
*** company-shell
this helps us with shells, and has specific support for [[fish]]
#+BEGIN_SRC emacs-lisp
  (use-package company-shell
    :config (add-to-list 'company-backends
			 '(company-shell
			   company-fish-shell
			   company-shell-env)))
#+END_SRC
*** company flx
#+begin_src emacs-lisp
  (use-package company-flx
    :requires flx
    :config (company-flx-mode +1))
#+end_src
** treemacs
#+begin_src emacs-lisp
  (use-package treemacs
    :chords ("\\\\" . treemacs))
#+end_src
*** treemacs evil
#+begin_src emacs-lisp
(use-package treemacs-evil)
#+end_src
*** treemacs projectile
#+begin_src emacs-lisp
  (use-package treemacs-projectile
    :chords ("\\p" . treemacs-projectile))
#+end_src

** emojify
#+begin_src emacs-lisp
(use-package emojify)
#+end_src
** all the icons
#+BEGIN_SRC emacs-lisp
  (use-package all-the-icons)
#+END_SRC
*** all the icons ivy
    [[ivy]]
    #+BEGIN_SRC emacs-lisp
      (use-package all-the-icons-ivy
	:config (all-the-icons-ivy-setup))
    #+END_SRC
** mode icons
#+begin_src emacs-lisp
  (use-package mode-icons
    :config (mode-icons-mode))
#+end_src
** flx
#+begin_src emacs-lisp
(use-package flx)
#+end_src

** git
#+BEGIN_SRC emacs-lisp
(use-package git)
#+END_SRC
** powerline
#+begin_src emacs-lisp
  (use-package powerline)
#+end_src
*** spaceline
#+BEGIN_SRC emacs-lisp
  (use-package spaceline
    :config (spaceline-spacemacs-theme))
#+END_SRC
** flycheck
#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :config (global-flycheck-mode))
#+END_SRC
*** flycheck-julia
    see also [[julia]]
#+BEGIN_SRC emacs-lisp
  (use-package flycheck-julia
    :config (flycheck-julia-setup))
#+END_SRC
** paradox
   Paradox is a nicer package list for package.el
   #+BEGIN_SRC emacs-lisp
     (use-package paradox)
   #+END_SRC
** magit
#+BEGIN_SRC emacs-lisp
(use-package magit)
#+END_SRC
** docker
#+BEGIN_SRC emacs-lisp
  (use-package docker
    :config (docker-global-mode))
  (use-package docker-tramp)
#+END_SRC
** kubernetes
#+BEGIN_SRC emacs-lisp
  (use-package kubernetes
    :commands (kubernetes-overview))

  (use-package kubernetes-evil
    :after kubernetes)
#+END_SRC
** spacemacs-theme
#+BEGIN_SRC emacs-lisp
  (use-package spacemacs-dark-theme
    :ensure spacemacs-theme)
#+END_SRC
** sr-speedbar
#+BEGIN_SRC emacs-lisp
(use-package sr-speedbar)
#+END_SRC
** projectile-speedbar
#+begin_src emacs-lisp
  (use-package projectile-speedbar
    :bind (:map evil-normal-state-map
                ("op" . projectile-speedbar-open-current-buffer-in-tree)))
#+end_src
* language support
** markdown
#+BEGIN_SRC emacs-lisp
(use-package markdown-mode)
#+END_SRC 
** c++
#+BEGIN_SRC emacs-lisp
  (use-package irony
    :hook
    (c++-mode . irony-mode)
    (c-mode . irony-mode)
    (objc-mode . irony-mode))
#+END_SRC
** rpm
#+BEGIN_SRC emacs-lisp
(use-package rpm-spec-mode)
#+END_SRC
** puppet
#+begin_src emacs-lisp
  (use-package puppet-mode)
#+end_src
** salt
#+begin_src emacs-lisp
(use-package salt-mode)
#+end_src
** nim
#+begin_src emacs-lisp
(use-package nim-mode)
#+end_src
** fish
#+BEGIN_SRC emacs-lisp
  (use-package fish-mode)
#+END_SRC
** ruby
#+begin_src emacs-lisp
(use-package robe
  :hook (ruby-mode . robe-mode))
#+end_src
** julia
#+BEGIN_SRC emacs-lisp
  (use-package julia-mode)
#+END_SRC
*** integrations
- [[flycheck-julia]]
** haskell
#+BEGIN_SRC emacs-lisp
  (use-package haskell-mode)
  (use-package intero
    :hook (haskell-mode . intero-mode))
#+END_SRC 
** meson
#+BEGIN_SRC emacs-lisp
(use-package meson-mode)
#+END_SRC
** lisps 
*** guile
#+BEGIN_SRC emacs-lisp
  (use-package paredit)
  (use-package geiser)
#+END_SRC
** web-mode
#+BEGIN_SRC emacs-lisp
  (use-package web-mode)
#+END_SRC
** dockerfiles
#+BEGIN_SRC emacs-lisp
  (use-package dockerfile-mode)
#+END_SRC
* customizations
** variable pitch fonts
   I really like variable pitched fonts (it's why I use emacs, so we're going
   to set them up to be the default here. Note that I want to use them for
   as much as possible, including code
   #+begin_src emacs-lisp
     (custom-set-faces
      '(default ((t (:family "DejaVu Sans")))))
   #+end_src
** diary file
#+BEGIN_SRC emacs-lisp

  (custom-set-variables
   '(diary-file "~/org/diary"))
#+END_SRC
